/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.egamorim.edish.infrastructure.messaging.schemas;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderRequested extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8440781434973810102L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderRequested\",\"namespace\":\"com.egamorim.edish.infrastructure.messaging.schemas\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"merchant_id\",\"type\":\"string\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderItem\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderRequested> ENCODER =
      new BinaryMessageEncoder<OrderRequested>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderRequested> DECODER =
      new BinaryMessageDecoder<OrderRequested>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderRequested> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderRequested> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderRequested>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderRequested to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderRequested from a ByteBuffer. */
  public static OrderRequested fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence merchant_id;
  @Deprecated public java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderRequested() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param merchant_id The new value for merchant_id
   * @param items The new value for items
   */
  public OrderRequested(java.lang.CharSequence id, java.lang.CharSequence merchant_id, java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> items) {
    this.id = id;
    this.merchant_id = merchant_id;
    this.items = items;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return merchant_id;
    case 2: return items;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: merchant_id = (java.lang.CharSequence)value$; break;
    case 2: items = (java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'merchant_id' field.
   * @return The value of the 'merchant_id' field.
   */
  public java.lang.CharSequence getMerchantId() {
    return merchant_id;
  }

  /**
   * Sets the value of the 'merchant_id' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.CharSequence value) {
    this.merchant_id = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> getItems() {
    return items;
  }

  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> value) {
    this.items = value;
  }

  /**
   * Creates a new OrderRequested RecordBuilder.
   * @return A new OrderRequested RecordBuilder
   */
  public static com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder newBuilder() {
    return new com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder();
  }

  /**
   * Creates a new OrderRequested RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderRequested RecordBuilder
   */
  public static com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder newBuilder(com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder other) {
    return new com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder(other);
  }

  /**
   * Creates a new OrderRequested RecordBuilder by copying an existing OrderRequested instance.
   * @param other The existing instance to copy.
   * @return A new OrderRequested RecordBuilder
   */
  public static com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder newBuilder(com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested other) {
    return new com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder(other);
  }

  /**
   * RecordBuilder for OrderRequested instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderRequested>
    implements org.apache.avro.data.RecordBuilder<OrderRequested> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence merchant_id;
    private java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[1].schema(), other.merchant_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.items)) {
        this.items = data().deepCopy(fields()[2].schema(), other.items);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderRequested instance
     * @param other The existing instance to copy.
     */
    private Builder(com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[1].schema(), other.merchant_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.items)) {
        this.items = data().deepCopy(fields()[2].schema(), other.items);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantId() {
      return merchant_id;
    }

    /**
      * Sets the value of the 'merchant_id' field.
      * @param value The value of 'merchant_id'.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder setMerchantId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.merchant_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_id' field has been set.
      * @return True if the 'merchant_id' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'merchant_id' field.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder clearMerchantId() {
      merchant_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> getItems() {
      return items;
    }

    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder setItems(java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem> value) {
      validate(fields()[2], value);
      this.items = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public com.egamorim.edish.infrastructure.messaging.schemas.OrderRequested.Builder clearItems() {
      items = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderRequested build() {
      try {
        OrderRequested record = new OrderRequested();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.merchant_id = fieldSetFlags()[1] ? this.merchant_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.items = fieldSetFlags()[2] ? this.items : (java.util.List<com.egamorim.edish.infrastructure.messaging.schemas.OrderItem>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderRequested>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderRequested>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderRequested>
    READER$ = (org.apache.avro.io.DatumReader<OrderRequested>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
